### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by JimSEOW** [exrin/Tesla-Mobile-App#1]
Can you include a page in the Tesla app that demonstrate the carouselview features discussed on your website using the latest Xamarin.Forms.CarouselView?

https://www.nuget.org/packages/Xamarin.Forms.CarouselView/2.3.0-pre1

**Comment by adamped** [comment]
In the last 24hrs James Montemagno just posted on the Xamarin Blog about it. This will be a better place to learn from it instead of here. https://blog.xamarin.com/flip-through-items-with-xamarin-forms-carouselview/

**Comment by JimSEOW** [comment]
thanks!
