### ISSUE TITLE
Typos?

### ISSUE THREAD

**Issue by AzureGulf** [exrin/Tesla-Mobile-App#2]
In StatusBarLabel.xaml.cs, presumably background is for StatusBar not the class:

        private void ResetVisualState()
        {
            // djw StatusBarLabel.BackgroundColor = Color.FromHex("#0173C7");
            StatusBar.BackgroundColor = Color.FromHex("#0173C7"); // djw
...

Also, a couple of missing/cannot find References in Tesla.Unit.Tests for:
     Microsoft.Pex.Framework
     Xamarin.Forms.Core

Removed and manually added ref to .dlls

**Comment by adamped** [comment]
Thanks, I removed PEX and added a proper reference to Xamarin.Forms.Core. As for the background color, the StatusBar is the progress bar label in StatusBarLabel that I reset the background color back to its original state. Unless I am not quite understanding?

**Comment by AzureGulf** [comment]
Thanks
