### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by zoemy** [exrin/Tesla-Mobile-App#3]
I'm getting some build errors like this in the TeslaDataBaseProject. Not sure how to fix it.
The type or namespace name 'Versioning' does not exist in the namespace 'System.Runtime' (are you missing an assembly reference?)

**Comment by adamped** [comment]
@zoemy - have you installed https://www.microsoft.com/net/core#windowsvs2015

**Comment by zoemy** [comment]
I didn't have the .NET Core tools preview . I've already install it and now I get this error about Autofac. I tried uninstalling Autofac and reinstalling it but I get the same error. How can I get around this?
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Autofac, Version=4.1.1.0, Culture=neutral, PublicKeyToken=17863af14b0044da'. Perhaps it doesn't exist in the Mono for Android profile?
Nombre de archivo: 'Autofac.dll'
   en Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   en Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   en Xamarin.Android.Tasks.ResolveAssemblies.Execute()	Tesla.Droid	C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	1410	
```

**Comment by adamped** [comment]
Upgrade to autofac 5.1.1 or whatever the latest is

**Comment by zoemy** [comment]
I've already done that but I get the same error

**Comment by adamped** [comment]
@zoemy - I updated the repo. Try again now.

**Comment by vasylmosiiuk** [comment]
Got a same error. After updating Nuget manager all're working. Another issue is that some of projects have a targeting on  .Net Standard 1.1 and another ones - .Net Standard 1.3, so simply change all projects targets on latest (1.3)

**Comment by adamped** [comment]
@vasylmosiiuk - the sample app has now been fixed to all target .net 1.3. Apologies, I checked in previously when I shouldn't have.
