### ISSUE TITLE
How to use VisualState and ModelState with Entry control input

### ISSUE THREAD

**Issue by vasylmosiiuk** [exrin/Tesla-Mobile-App#4]
@adamped Maybe it's a stupid question, but in TeslaApp I saw only demo how to update Label.Text using VisualState property (which was updated by property changed request from ModelState, i.e. PinViewModel.VisualState.Pin). What is workaround for TwoWay VisualState's properties bindings like a Entry.TextProperty?

**Comment by adamped** [comment]
You need to download Exrin 1.1.1 and then add a Binding property, with TwoWay binding.

e.g. 

[Binding(BindingType.TwoWay)]
public int PropertyName { get { Get<int>(); } set { Set(value); } }

This will propagate it back up to the ModelState. By default, it only propagates to the VisualState and not back up.
